application: iap-hello-world
version: 1-4
runtime: python
api_version: 1

handlers:
# precedence should be noted for any wildcards
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /javascripts
  static_dir: javascripts

- url: /versions/templates
  static_dir: versions/templates
  mime_type: "text/plain"

- url: /versions
  static_dir: versions

- url: /source
  static_dir: source
  login: required
  mime_type: "application/zip"

- url: /play
  script: main.py
  login: required

- url: /build-level
  script: main.py
  login: required

- url: /instructions
  script: main.py
  login: required

- url: /.*
  script: main.py
